### ISSUE TITLE
Bottleneck: Large loads

### ISSUE THREAD

**Issue by NicholasFry** [j-c-cook/ghedt#110]
**Describe the bug**
There seems to be a significant increase in runtimes for large loads. (400-700 tons) I assume this is a bottleneck, but I recall running similarly large loads in v0.1 with relative ease. I am including a load profile to test. The Atlanta building example still runs fine. (~700-900 seconds for this)

Perhaps this is normal, given the restrictive nature of the constraints.

**To Reproduce**
- Version of `ghedt`: `ghedt-v0.3` 
- The python file (please attach or link to an existing example file)
https://github.com/NicholasFry/Other/blob/main/place.py

**Error message**
Please provide either a screen shot of the error message or copy and paste in the message below:
```
ghedt\ground_heat_exchangers.py:168: RuntimeWarning: invalid value encountered in log g_values = g(np.log((_time * 3600.) / ts))
```

**Additional context**
- Attach any additional files such as a load file containing 8760 hourly loads
[demand_place.csv](https://github.com/j-c-cook/ghedt/files/10505878/demand_place.csv)

**Comment by j-c-cook** [comment]
@NicholasFry Thank you for the detailed description. I'll work on this over the weekend and get back to you on what I find out.

**Comment by j-c-cook** [comment]
@NicholasFry The large amount of time to perform the search in your script is not due to the loads, it is due to the value of  `B_min` resulting in the largest field in the search domain being 13,000+ boreholes. After setting `B_min=5.`, the calculation time required to find a rectangle and size it is 7.98 seconds on my laptops i7-11850H. I get the following output printed to the console:
```
Find rectangle...
=================
/home/jackcook/Documents/ghedt/ghedt/ground_heat_exchangers.py:168: RuntimeWarning: invalid value encountered in log
  g_values = g(np.log((_time * 3600.) / ts))
* Single U-tube
---------------
Calculation time: 7.98 seconds
Height: 115.1082 meters
Number of boreholes: 432
Total Drilling: 49726.7 meters


Process finished with exit code 0
```

I've added user information that will be printed to the console if the maximum number of boreholes in the domain exceeds 2500 in PR https://github.com/j-c-cook/ghedt/pull/111. Direct feedback from the tool on design tips like this are something `ghedt` can benefit from. 

The `numpy` warning about the interpolation has an open issue https://github.com/j-c-cook/ghedt/issues/82. I will address the warning there, but will likely use the load profile you provide here to debug that process.

**Comment by NicholasFry** [comment]
I understand. That makes sense. Thank you for looking into this.
