### ISSUE TITLE
find_near_square.py

### ISSUE THREAD

**Issue by NicholasFry** [j-c-cook/ghedt#97]
Running examples/Design/find_near_square.py is throwing me an AttributeError for length_of_side on line 132. It seems like everything is in order to me, inside of utilities.py but the error is there, nonetheless. 
`File ".\find_near_square.py", line 132, in main
    length = dt.utilities.length_of_side(number_of_boreholes, B)
AttributeError: module 'ghedt.utilities' has no attribute 'length_of_side'`

**Comment by j-c-cook** [comment]
Have you installed `v0.1` from PyPi or did you clone the repository?

**Comment by j-c-cook** [comment]
@NicholasFry I ask because the current `find_near_square.py` in the [main](https://github.com/j-c-cook/ghedt/blob/main/ghedt/examples/Design/find_near_square.py) branch is using functions that didn't exist in `v0.1`. If you have ran `pip install ghedt` (accessing [PyPi](https://pypi.org/project/ghedt/)) then you'll need utilize the examples located in the [version 0.1 release](https://github.com/j-c-cook/ghedt/releases/tag/v0.1).

**Comment by NicholasFry** [comment]
You are moving quickly! I cloned into a new environment, and it works beautifully. Thanks.
